language: python

matrix:
  include:
    - os: linux
      language: python
      python: "3.6.1"

    - os: linux
      language: python
      python: "3.6.2"

install:
 - pip install pylint

before_script:
 - pylint --version

script:
 - pylint main.py
   make test
